bg_scene_path: "/root/output_models/place_object/gaussian_splatting/mipnerf_360/garden"
bg_gaussians_path: "/root/output_models/place_object/gaussian_splatting/mipnerf_360/garden/point_cloud/iteration_7000/point_cloud.ply"
object_scene_path: "/root/output_models/place_object/gaussian_splatting/nerf_synthetic/chair"
object_gaussians_path: "/root/output_models/place_object/gaussian_splatting/nerf_synthetic/chair/point_cloud/iteration_30000/point_cloud.ply"
object_mask_path: "/root/projects/third_party/GracoNet-Object-Placement/chair_in_garden_msk.png"
object_on_bg_img_path: "/root/projects/third_party/GracoNet-Object-Placement/chair_in_garden_img.png"
depth_scale_range:
  start: 1.
  end: 3.5
  step: 0.1
resolution:
  width: 1600
  height: 1036
cams:
  main_cam_id: 0
  second_cam_id: 14